version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - sqlite-data:/app/data
    environment:
      - DB_PATH=/app/data/database.sqlite
    depends_on:
      - sqlite

  sqlite:
    image: keinos/sqlite3:latest
    volumes:
      - sqlite-data:/data
    command: ["tail", "-f", "/dev/null"]  # Keeps container running

volumes:
  sqlite-data: