version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - sqlite-data:/app/data
    environment:
      - CONFIG_PATH=/app/config/local.yaml
      - DB_PATH=/app/data/database.sqlite

volumes:
  sqlite-data: